import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useQuery } from "@tanstack/react-query";
import { Users, UserCheck, TrendingUp, Calendar, Clock, FileText, CreditCard, UserMinus } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { PageHeader } from "@/components/ui/page-header";
import { getAnalyticsSummary } from "@/modules/analytics/services/analyticsApi";
import { Skeleton } from "@/components/ui/skeleton";
function MetricCard({ label, value, sub, icon: Icon, accent, }) {
    return (_jsx(Card, { children: _jsxs(CardContent, { className: "flex items-start gap-3 p-4", children: [Icon && (_jsx("div", { className: `flex size-10 shrink-0 items-center justify-center rounded-xl ${accent ?? "bg-brand-50 text-brand-600"}`, children: _jsx(Icon, { className: "size-5" }) })), _jsxs("div", { className: "min-w-0 flex-1", children: [_jsx("p", { className: "text-[11px] font-semibold uppercase tracking-wide text-slate-400", children: label }), _jsx("p", { className: "mt-0.5 text-2xl font-extrabold tracking-tight text-slate-800", children: value }), sub && _jsx("p", { className: "mt-0.5 text-[11px] text-slate-400", children: sub })] })] }) }));
}
function RowStat({ label, value }) {
    return (_jsxs("div", { className: "flex items-center justify-between py-2 text-sm", children: [_jsx("span", { className: "text-slate-500", children: label }), _jsx("span", { className: "font-semibold text-slate-800", children: value })] }));
}
export function PaginaDashboard() {
    const { data, isLoading } = useQuery({ queryKey: ["analytics-summary"], queryFn: getAnalyticsSummary });
    const fmt = (n) => n !== undefined ? n.toLocaleString("es-PE") : "—";
    const pct = (n) => n !== undefined ? `${(n * 100).toFixed(1)}%` : "—";
    const money = (n) => n !== undefined ? `S/ ${n.toLocaleString("es-PE", { minimumFractionDigits: 2 })}` : "—";
    if (isLoading) {
        return (_jsxs("section", { className: "space-y-6", children: [_jsx(PageHeader, { title: "Dashboard", description: "Resumen general del sistema" }), _jsx("div", { className: "grid gap-4 sm:grid-cols-2 lg:grid-cols-4", children: Array.from({ length: 8 }).map((_, i) => (_jsx(Skeleton, { className: "h-24 rounded-xl" }, i))) })] }));
    }
    return (_jsxs("section", { className: "space-y-6", children: [_jsx(PageHeader, { title: "Dashboard", description: "Resumen general del sistema RRHH" }), _jsxs("div", { className: "grid gap-4 sm:grid-cols-2 lg:grid-cols-4", children: [_jsx(MetricCard, { label: "Empleados totales", value: fmt(data?.totalEmployees), icon: Users, accent: "bg-brand-50 text-brand-600" }), _jsx(MetricCard, { label: "Empleados activos", value: fmt(data?.activeEmployees), icon: UserCheck, accent: "bg-emerald-50 text-emerald-600" }), _jsx(MetricCard, { label: "Nuevos este mes", value: fmt(data?.newHiresThisMonth), icon: TrendingUp, accent: "bg-blue-50 text-blue-600" }), _jsx(MetricCard, { label: "Bajas este mes", value: fmt(data?.terminationsThisMonth), icon: UserMinus, accent: "bg-rose-50 text-rose-600" }), _jsx(MetricCard, { label: "Tasa asistencia", value: pct(data?.attendanceRate), icon: Clock, accent: "bg-amber-50 text-amber-600", sub: `Tardanzas: ${pct(data?.lateRate)}` }), _jsx(MetricCard, { label: "Vacaciones pendientes", value: fmt(data?.pendingVacations), icon: Calendar, accent: "bg-violet-50 text-violet-600" }), _jsx(MetricCard, { label: "Permisos pendientes", value: fmt(data?.pendingLeaves), icon: FileText, accent: "bg-sky-50 text-sky-600" }), _jsx(MetricCard, { label: "Reclutamientos abiertos", value: fmt(data?.openRecruitments), icon: Users, accent: "bg-teal-50 text-teal-600" })] }), _jsxs("div", { className: "grid gap-4 sm:grid-cols-2", children: [_jsxs(Card, { children: [_jsx(CardHeader, { children: _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(CreditCard, { className: "size-4 text-brand-500" }), _jsx(CardTitle, { children: "Planilla" })] }) }), _jsxs(CardContent, { className: "divide-y divide-slate-100", children: [_jsx(RowStat, { label: "Costo total", value: money(data?.totalPayrollCost) }), _jsx(RowStat, { label: "Promedio por empleado", value: money(data?.averagePayrollCost) })] })] }), _jsxs(Card, { children: [_jsx(CardHeader, { children: _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Clock, { className: "size-4 text-brand-500" }), _jsx(CardTitle, { children: "Pendientes de aprobaci\u00F3n" })] }) }), _jsxs(CardContent, { className: "divide-y divide-slate-100", children: [_jsx(RowStat, { label: "Vacaciones por aprobar", value: fmt(data?.pendingVacations) }), _jsx(RowStat, { label: "Permisos por aprobar", value: fmt(data?.pendingLeaves) }), _jsx(RowStat, { label: "Documentos pendientes", value: fmt(data?.pendingDocuments) })] })] })] })] }));
}
