import type { OrgItem, OrgPayload, OrgQuery, PagedResult } from "@/modules/org-structure/types/orgStructure.types";
export declare function getAreas(query: OrgQuery): Promise<PagedResult<OrgItem>>;
export declare function createArea(payload: OrgPayload): Promise<OrgItem>;
export declare function updateArea(id: string, payload: OrgPayload): Promise<OrgItem>;
export declare function updateAreaStatus(id: string, isActive: boolean): Promise<void>;
export declare function deleteArea(id: string): Promise<void>;
export declare function getPositions(query: OrgQuery): Promise<PagedResult<OrgItem>>;
export declare function createPosition(payload: OrgPayload): Promise<OrgItem>;
export declare function updatePosition(id: string, payload: OrgPayload): Promise<OrgItem>;
export declare function updatePositionStatus(id: string, isActive: boolean): Promise<void>;
export declare function deletePosition(id: string): Promise<void>;
