import type { CreateTemplatePayload, OnboardingProcess, OnboardingTemplate, StartProcessPayload, UpdateTemplatePayload } from "@/modules/onboarding/types/onboarding.types";
export declare function getOnboardingTemplates(): Promise<OnboardingTemplate[]>;
export declare function createOnboardingTemplate(payload: CreateTemplatePayload): Promise<OnboardingTemplate>;
export declare function deleteOnboardingTemplate(id: string): Promise<void>;
export declare function updateOnboardingTemplate(id: string, payload: UpdateTemplatePayload): Promise<OnboardingTemplate>;
export declare function duplicateOnboardingTemplate(id: string): Promise<OnboardingTemplate>;
export declare function updateOnboardingTemplateStatus(id: string, isActive: boolean): Promise<void>;
export declare function getOnboardingProcesses(employeeId?: string): Promise<OnboardingProcess[]>;
export declare function getOnboardingProcess(id: string): Promise<OnboardingProcess>;
export declare function startOnboardingProcess(payload: StartProcessPayload): Promise<OnboardingProcess>;
export declare function completeOnboardingTask(processId: string, taskId: string): Promise<void>;
export declare function completeOnboardingProcess(processId: string): Promise<void>;
export declare function cancelOnboardingProcess(processId: string): Promise<void>;
