namespace Hrms.Application.DTOs.Configuration;

public sealed record ConfigurationItemDto(
    Guid Id,
    string Code,
    string Name,
    bool IsActive,
    int EmployeesCount,
    string? BranchType = null,
    string? Description = null,
    string? Country = null,
    string? Region = null,
    string? City = null,
    string? Address = null,
    string? Phone = null,
    string? Email = null,
    string? ResponsibleName = null,
    string? ResponsibleTitle = null,
    int? Capacity = null,
    string? BusinessHours = null,
    string? CostCenter = null,
    DateTime? OpenedAtUtc = null,
    bool VisibleForAssignments = true,
    bool RequiresApprovalForChanges = false,
    DateTime? CreatedAtUtc = null,
    DateTime? UpdatedAtUtc = null,
    string? CreatedBy = null,
    string? UpdatedBy = null);
