import type { ConfigurationCatalogItem, ConfigurationCatalogPayload, ConfigurationQuery, GeneralSettingItem, GeneralSettingPayload, PagedResult } from "@/modules/configuration/types/configuration.types";
export declare function getBranches(query: ConfigurationQuery): Promise<PagedResult<ConfigurationCatalogItem>>;
export declare function createBranch(payload: ConfigurationCatalogPayload): Promise<ConfigurationCatalogItem>;
export declare function updateBranch(id: string, payload: ConfigurationCatalogPayload): Promise<ConfigurationCatalogItem>;
export declare function updateBranchStatus(id: string, isActive: boolean): Promise<void>;
export declare function deleteBranch(id: string): Promise<void>;
export declare function getContractTypes(query: ConfigurationQuery): Promise<PagedResult<ConfigurationCatalogItem>>;
export declare function createContractType(payload: ConfigurationCatalogPayload): Promise<ConfigurationCatalogItem>;
export declare function updateContractType(id: string, payload: ConfigurationCatalogPayload): Promise<ConfigurationCatalogItem>;
export declare function updateContractTypeStatus(id: string, isActive: boolean): Promise<void>;
export declare function deleteContractType(id: string): Promise<void>;
export declare function getGeneralSettings(): Promise<GeneralSettingItem[]>;
export declare function upsertGeneralSetting(key: string, payload: GeneralSettingPayload): Promise<GeneralSettingItem>;
export declare function deleteGeneralSetting(id: string): Promise<void>;
