import type { DocumentTemplate, CreateTemplatePayload, EmployeeDocument, CreateDocumentPayload } from "@/modules/documents/types/documents.types";
export declare function getDocumentTemplates(): Promise<DocumentTemplate[]>;
export declare function createDocumentTemplate(payload: CreateTemplatePayload): Promise<DocumentTemplate>;
export declare function deleteDocumentTemplate(id: string): Promise<void>;
export declare function getDocuments(employeeId: string, status: string): Promise<EmployeeDocument[]>;
export declare function getDocument(id: string): Promise<EmployeeDocument>;
export declare function createDocument(payload: CreateDocumentPayload): Promise<EmployeeDocument>;
export declare function sendForSignature(id: string): Promise<void>;
export declare function signDocument(id: string): Promise<void>;
export declare function rejectDocument(id: string, reason: string): Promise<void>;
export declare function getMyDocuments(): Promise<EmployeeDocument[]>;
