import type { EvaluationCycle, CreateCyclePayload, EvaluationAssignment, CreateAssignmentPayload, SubmitSelfEvaluationPayload, SubmitEvaluatorEvaluationPayload, FinalizeEvaluationPayload } from "@/modules/evaluations/types/evaluations.types";
export declare function getCycles(): Promise<EvaluationCycle[]>;
export declare function createCycle(payload: CreateCyclePayload): Promise<EvaluationCycle>;
export declare function activateCycle(id: string): Promise<void>;
export declare function closeCycle(id: string): Promise<void>;
export declare function getAssignments(cycleId: string, employeeId: string): Promise<EvaluationAssignment[]>;
export declare function createAssignment(payload: CreateAssignmentPayload): Promise<EvaluationAssignment>;
export declare function submitSelfEvaluation(id: string, payload: SubmitSelfEvaluationPayload): Promise<EvaluationAssignment>;
export declare function submitEvaluatorEvaluation(id: string, payload: SubmitEvaluatorEvaluationPayload): Promise<EvaluationAssignment>;
export declare function finalizeEvaluation(id: string, payload: FinalizeEvaluationPayload): Promise<EvaluationAssignment>;
export declare function getMyEvaluations(): Promise<EvaluationAssignment[]>;
